# Cat visit to the vet themed bingo

c(
  "Cat name Fluffy",
  "Cat name Snowball",
  "Cat name Mittens",
  "Cat name Princess",
  "Cat name Precious",
  "Bengal",
  "Main Coon",
  "DSH",
  "DLH",
  "Friendly",
  "Purring",
  "Won't come out of crate",
  "Won't go into crate",
  "Got scratched",
  "Yowling scares other clients",
  "Hissing",
  "Get frisky with catnip",
  "Sits quietly for exam",
  "Heart rate over 180",
  "Nail trim",
  "Cat fight abscess",
  "Lion cut",
  "Looks ridiculous with a lion cut",
  "Need tech to help",
  "Escapes exam room",
  "Staff ends up bleeding",
  "Tell owner 'its not your fault'",
  "Vaccinated yourself",
  "Used blankets",
  "Used cat gloves",
  "Cuddly cat",
  "Excited for return visit",
  "Adorable kitten",
  "Lovable senior",
  "Cute at middle age"
)
